# Generated by Django 3.0.7 on 2020-06-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
